services:
    backend:
        volumes:
            - ./backend/migrations:/app/migrations
            - ./backend/src:/app/src
            - ./backend/vendor:/app/vendor
            - ./backend/bin:/app/bin
