server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /app/index.html {
        add_header Cache-Control "no-cache" always;
        try_files $uri =404;
    }

    location ~* "\.(js|css|woff2)$" {
        etag off;
        if_modified_since off;
        add_header Cache-Control "public, max-age=31536000, immutable";
        access_log off;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /app/index.html;
    }
}
