base: /
baseVariants:
  -
    base: 'https://www.ukolio.com'
    condition: 'applicationContext == "Production"'
  -
    base: 'https://localhost:7281'
    condition: 'applicationContext == "Development"'
dependencies:
  - typo3/fluid-styled-content
  - typo3/seo-sitemap
  - tpwd/ke_search
  - marekskopal/typo3-features
  - marekskopal/typo3-google-font
  - marekskopal/typo3-pricing
  - marekskopal/typo3-faq
  - marekskopal/typo3-core
  - marekskopal/typo3-web
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=3'
languages:
  -
    title: English
    enabled: true
    locale: en_US
    hreflang: en
    base: /
    websiteTitle: Ukolio
    navigationTitle: EN
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
    languageId: 0
  -
    title: Czech
    enabled: true
    locale: cs_CZ
    hreflang: cs
    base: /cs/
    baseVariants:
      -
        base: 'https://www.ukolio.com/cs/'
        condition: 'applicationContext == "Production"'
      -
        base: 'https://localhost:443/cs/'
        condition: 'applicationContext == "Development"'
    websiteTitle: Ukolio
    navigationTitle: CS
    fallbackType: fallback
    fallbacks: '0'
    flag: cz
    languageId: 1
rootPageId: 1
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nSitemap: https://www.ukolio.com/sitemap.xml"
  -
    route: sitemap.xml
    type: uri
    source: 'https://www.ukolio.com/?type=1533906435'
websiteTitle: Ukolio
